/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pomodoro;

import java.awt.Cursor;
import java.awt.Desktop;
import java.net.URI;
import java.awt.Toolkit;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;


/**
 *
 * @author XZuicer_Jr
 */

public class pomodoroUI extends javax.swing.JFrame {
    Timer timer;
    int pomodoroNo; //keeps track of the number of pomodoro intervals completed
    int cicleNo = 0; //keeps track of the number of cicles completed (4 pomodoro)
    boolean paused;
    
    /**
     * Creates new form pomodoroUI
     */
    
    public pomodoroUI() {
        initComponents();
        lblCreator.setCursor(new Cursor(Cursor.HAND_CURSOR));
        PomoMin.setValue(25);
        ShortMin.setValue(5);
        LongMin.setValue(15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPomoTime = new javax.swing.JLabel();
        lblShortBrakeTime = new javax.swing.JLabel();
        lblLongBrakeTime = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PomoMin = new javax.swing.JSpinner();
        PomoSeg = new javax.swing.JSpinner();
        ShortSeg = new javax.swing.JSpinner();
        ShortMin = new javax.swing.JSpinner();
        LongMin = new javax.swing.JSpinner();
        LongSeg = new javax.swing.JSpinner();
        lblSeparador = new javax.swing.JLabel();
        lblSeparador1 = new javax.swing.JLabel();
        lblSeparador2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTimer = new javax.swing.JLabel();
        lblActualTimer = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblDevelop = new javax.swing.JLabel();
        lblCreator = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblPomodoroTittle = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miQuit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POMODORO");

        lblPomoTime.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblPomoTime.setForeground(new java.awt.Color(185, 0, 0));
        lblPomoTime.setText("Pomodoro Time:");

        lblShortBrakeTime.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblShortBrakeTime.setForeground(new java.awt.Color(185, 0, 0));
        lblShortBrakeTime.setText("Short Break Time:");

        lblLongBrakeTime.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblLongBrakeTime.setForeground(new java.awt.Color(185, 0, 0));
        lblLongBrakeTime.setText("Long Break Time:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShortBrakeTime, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLongBrakeTime, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPomoTime, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPomoTime)
                .addGap(18, 18, 18)
                .addComponent(lblShortBrakeTime)
                .addGap(18, 18, 18)
                .addComponent(lblLongBrakeTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        PomoMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));
        PomoMin.setToolTipText("");

        PomoSeg.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        ShortSeg.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        ShortMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        LongMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        LongSeg.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        lblSeparador.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblSeparador.setText(":");

        lblSeparador1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblSeparador1.setText(":");

        lblSeparador2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblSeparador2.setText(":");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PomoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSeparador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PomoSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ShortMin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSeparador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShortSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LongMin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSeparador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LongSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PomoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PomoSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeparador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShortMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShortSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeparador1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LongMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LongSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeparador2))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        PomoMin.getAccessibleContext().setAccessibleName("");

        lblTimer.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTimer.setText("TIMER:");

        lblActualTimer.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblActualTimer.setText("00:00");
        lblActualTimer.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblTimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblActualTimer)
                .addGap(53, 53, 53))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimer)
                    .addComponent(lblActualTimer))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(153, 153, 153));

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnPause.setText("Pause");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPause)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnPause)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblDevelop.setText("Developed by:");

        lblCreator.setForeground(new java.awt.Color(0, 119, 187));
        lblCreator.setText("@Xzuicer_Jr");
        lblCreator.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCreator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreatorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDevelop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreator)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDevelop)
                    .addComponent(lblCreator))
                .addContainerGap())
        );

        lblPomodoroTittle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblPomodoroTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPomodoroTittle.setText("POMODORO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPomodoroTittle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblPomodoroTittle)
                .addGap(14, 14, 14))
        );

        jMenu1.setText("Pomodoro");
        jMenu1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        miAbout.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        miAbout.setText("About");
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        jMenu1.add(miAbout);
        jMenu1.add(jSeparator2);

        miQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        miQuit.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        miQuit.setText("Quit");
        miQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQuitActionPerformed(evt);
            }
        });
        jMenu1.add(miQuit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    public void setTime(int time) { //function to display timer   
        long timeNow = 1000*time;
        long second = (timeNow / 1000) % 60;
        long minute = (timeNow / (1000 * 60)) % 60;
        lblActualTimer.setText(String.format("%02d:%02d", minute, second));
    }
    
    public void pomodoroTimer() { //runs for pomodoro time  
        timer = new Timer();
        timer.schedule(new TimerTask() {
            int counter = 0;
            String pomoMin = PomoMin.getValue().toString();
            String pomoSeg = PomoSeg.getValue().toString();
            int counterLimit = Integer.parseInt(pomoMin)*60 + Integer.parseInt(pomoSeg);

            @Override
            public void run() {   
                if(!paused) { 
                    ++counter;
                    setTime(counter);
                    if(counter == counterLimit && pomodoroNo < 4) { //if less than 4 pomodoros are complete, take a short break   
                        timer.cancel();
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(null,"You have completed a pomodoro! Take a short break!");
                        shortBreakTimer();
                        pomodoroNo ++;
                    } else if (counter == counterLimit && pomodoroNo == 4) { //if 4 pomodoros are complete, take a long break
                        timer.cancel();
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(null,"You have completed 4 pomodoros! Take a long break!");
                        longBreakTimer();
                    }
                }   
            }
        },0,1000);
            
    }

    public void shortBreakTimer() { //runs for short-break time   
        timer = new Timer();
        timer.schedule(new TimerTask() {
            int counter = 0;
            String shortMin = ShortMin.getValue().toString();
            String shortSeg = ShortSeg.getValue().toString();
            int counterLimit = Integer.parseInt(shortMin)*60 + Integer.parseInt(shortSeg);

            @Override
            public void run() {   
                if (!paused) {
                    ++counter;
                    setTime(counter);
                    if(counter == counterLimit) {  
                        timer.cancel();
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(null,"Time up! Resume work.");
                        pomodoroTimer();
                    }
                }
            }
        },0,1000); 
        
    }
    
    public void longBreakTimer() { //runs for long break timer
        timer = new Timer();
        timer.schedule(new TimerTask() {
            int counter = 0;
            String longMin = LongMin.getValue().toString();
            String longSeg = LongSeg.getValue().toString();
            int counterLimit = Integer.parseInt(longMin)*60 + Integer.parseInt(longSeg);
            
            @Override
            public void run() {  
                if(!paused) {
                    ++counter;
                    setTime(counter);
                    if(counter == counterLimit) {   
                        timer.cancel();
                        Toolkit.getDefaultToolkit().beep();
                        cicleNo++;
                        JOptionPane.showMessageDialog(null,"Time up! Good job! you already complete (" + cicleNo + ") cicles today");
                        pomodoroNo = 1;
                        timer.cancel();
                        lblActualTimer.setText("00:00");
                        PomoMin.setEnabled(true);
                        PomoSeg.setEnabled(true);
                        ShortMin.setEnabled(true);
                        ShortSeg.setEnabled(true);
                        LongMin.setEnabled(true);
                        LongSeg.setEnabled(true);
                        btnStart.setEnabled(true);
                        btnPause.setEnabled(false);
                        btnReset.setEnabled(true);
                    }
                }
            }
        },0,1000);
  
    }

    private void lblCreatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreatorMouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://twitter.com/xzuicer_jr"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblCreatorMouseClicked

    private void miQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miQuitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        PomoMin.setEnabled(true);
        PomoSeg.setEnabled(true);
        ShortMin.setEnabled(true);
        ShortSeg.setEnabled(true);
        LongMin.setEnabled(true);
        LongSeg.setEnabled(true);
        PomoMin.setValue(25);
        PomoSeg.setValue(0);
        ShortMin.setValue(5);
        ShortSeg.setValue(0);
        LongMin.setValue(15);
        LongSeg.setValue(0);
        timer.cancel();
        lblActualTimer.setText("00:00");
        btnStart.setEnabled(true);
        btnPause.setEnabled(false);
        btnReset.setEnabled(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        JOptionPane.showMessageDialog(this, "POMODORO TIMER\nVersion: 0.1\nJanuary - 2021\n\nDeveloped by: @Xzuicer_Jr", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_miAboutActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        PomoMin.setEnabled(false);
        PomoSeg.setEnabled(false);
        ShortMin.setEnabled(false);
        ShortSeg.setEnabled(false);
        LongMin.setEnabled(false);
        LongSeg.setEnabled(false);
        btnStart.setEnabled(false);
        btnPause.setEnabled(true);
        btnReset.setEnabled(true);
        pomodoroTimer();
        pomodoroNo = 1;
        paused = false;
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        if(!paused) {
            paused = true;
            btnPause.setText("Unpause");
            btnReset.setEnabled(false);
        } else {
            paused = false;
            btnPause.setText("Pause");
            btnReset.setEnabled(true);
        }
    }//GEN-LAST:event_btnPauseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pomodoroUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pomodoroUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pomodoroUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pomodoroUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pomodoroUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner LongMin;
    private javax.swing.JSpinner LongSeg;
    private javax.swing.JSpinner PomoMin;
    private javax.swing.JSpinner PomoSeg;
    private javax.swing.JSpinner ShortMin;
    private javax.swing.JSpinner ShortSeg;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStart;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblActualTimer;
    private javax.swing.JLabel lblCreator;
    private javax.swing.JLabel lblDevelop;
    private javax.swing.JLabel lblLongBrakeTime;
    private javax.swing.JLabel lblPomoTime;
    private javax.swing.JLabel lblPomodoroTittle;
    private javax.swing.JLabel lblSeparador;
    private javax.swing.JLabel lblSeparador1;
    private javax.swing.JLabel lblSeparador2;
    private javax.swing.JLabel lblShortBrakeTime;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miQuit;
    // End of variables declaration//GEN-END:variables
}
